services:
  airflow-standalone:
    build: .
    container_name: airflow_local_standalone
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DAG_PROCESSOR__HEALTH_CHECK_THRESHOLD=120
    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - ./airflow_passwords.json:/opt/airflow/simple_auth_manager_passwords.json.generated
    ports:
      - "8080:8080"
    # command: standalone
    user: "${AIRFLOW_UID}:0"
