[project]
name = "taxi-longest-trip"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
    "pandas>=3.0.6",
    "pyarrow>=25.0.1",
    "SQLAlchemy>=2.1.4",
    "psycopg2-binary>=2.9.9",
    "apache-airflow-providers-postgres>=4.0.0"
]

[dependency-groups]
dev = [
    "black>=26.10.0",
    "ruff>=0.16.10",
    "dagruff>=1.0.0"
]
airflow-dev = [
    "apache-airflow==3.3.2"
]
test = [
    "pytest>=9.1.1",
    "apache-airflow==3.3.2"
]

streamlit = [
    "psycopg[binary]>=3.3.6",
    "pandas>=3.0.6",
    "streamlit>=1.65.0",
    "streamlit-autorefresh>=1.0.1"
]